In [1]:
"""
filename: wsh_earnings_eps_eadates.ipynb

This is potentially draft code and prepare for what's
to come with getting this data from WSH.

"""
# Imports here
import pandas as pd
import glob, os
import numpy as np
import datetime
from datetime import timedelta
import time 
import re

# OneDrive path here
pth = "C:\\Users\clj585\OneDrive - Northwestern University\data_feeds\WSH\Data"
os.chdir(pth)

In [2]:
"""
Get all of the earnings and EPS files in parquet format from directory. 

These files are the more recent history. Some overlaps because these 
daily files are throughout the 2021 year. 

The historic data stopped around 8/3/2021 - need de-duplicate later on. 

"""
# Use glob to pick out files by ending 
earn_files = glob.glob("*_ED.parquet")
eps_files = glob.glob("*_EPS.parquet")

# Save and concatenate all dataframes here by type 
earn_list = []
eps_list = []

# Loop over earnings parquet daily files
for file in earn_files:
    temp = pd.read_parquet(os.path.join(pth, file))
    # Very important step: create the "date" column to get it in snapshot form 
    temp['asofdate'] = re.findall(r'\d{1,2}\-\d{1,2}\-\d{4}', file)[0]
    earn_list.append(temp)
    
# Repeat loop over EPS parquet daily files 
for file in eps_files:
    temp = pd.read_parquet(os.path.join(pth, file))
    eps_list.append(temp)
    
# Join everything together in the lists
wsh_eps = pd.concat(eps_list)
wsh_earn = pd.concat(earn_list)
wsh_earn = wsh_earn[['event_id', 'company_id', 'stock_symbol', 'asofdate',
                    'isin','company_name', 'earnings_date', 'quarter', 
                    'fiscal_year', 'earnings_date_status', 'time_of_day', 
                    'audit_source', 'announce_datetime','prelim_earnings_date',
                     'updated', 'created']]
wsh_earn

,event_id,company_id,stock_symbol,asofdate,isin,company_name,earnings_date,quarter,fiscal_year,earnings_date_status,time_of_day,audit_source,announce_datetime,prelim_earnings_date,updated,created
0,3VLF70OU,1431693492,JDW.GB,10-1-2021,GB0001638955,JD Wetherspoon Plc,10/01/2021,H2,2021,CONFIRMED,Unspecified,NEWS,07/12/2021,NaN,10/02/2021 01:13:07 AM,09/15/2018 09:15:56 AM
1,432UBI6H,1431695716,9793.JP,10-1-2021,JP3485600005,Daiseki Co. Ltd.,10/01/2021,Q2,2022,CONFIRMED,Unspecified,NEWS,08/25/2021,NaN,10/02/2021 01:13:07 AM,06/14/2019 10:57:19 AM
2,4IQK55K7,1431699366,KOF.FR,10-1-2021,FR0004007813,Kaufman & Broad,10/01/2021,Q3,2021,CONFIRMED,Unspecified,NEWS,07/30/2021,NaN,10/02/2021 09:49:53 AM,09/08/2021 04:22:18 PM
3,4AVG1QHW,1431696478,ANPC,10-1-2021,US03635R1077,"AnPac Bio-Medical Science Co., Ltd.",10/01/2021,H1,2021,CONFIRMED,Before Market,NEWS,10/01/2021 07:30 AM,NaN,10/02/2021 01:13:07 AM,07/16/2020 08:51:51 AM
4,4IQP3M6J,1431699533,7965.JP,10-1-2021,JP3437400009,Zojirushi,10/01/2021,Q3,2021,CONFIRMED,Unspecified,NEWS,None,NaN,10/02/2021 01:13:07 AM,09/13/2021 03:38:36 PM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,430BA9DI,1431695482,SY,9-9-2021,US83356Q1085,So-Young International Inc.,09/10/2021,Q2,2021,CONFIRMED,Before Market,NEWS,08/30/2021 06:00 AM,None,09/11/2021 01:11:14 AM,05/23/2019 10:20:18 AM
74,42ZYEKOT,1431695358,TIGR,9-9-2021,US91531W1062,UP Fintech Holding Limited,09/10/2021,Q2,2021,CONFIRMED,Before Market,NEWS,08/27/2021 02:19 AM,None,09/11/2021 01:11:14 AM,05/10/2019 01:19:10 PM
75,4IQP2HSR,1431697541,INAB,9-9-2021,US45674E1091,"IN8bio, Inc.",09/10/2021,Q2,2021,CONFIRMED,After Market,NEWS,09/10/2021 04:15 PM,None,09/13/2021 11:28:30 AM,09/13/2021 11:28:30 AM
76,4IQP3KK7,1431699548,SGMA,9-9-2021,US82661L1017,Sigmatron International Inc.,09/10/2021,Q1,2022,CONFIRMED,During Market,NEWS,09/10/2021 11:20 AM,None,09/13/2021 01:43:13 PM,09/13/2021 01:43:13 PM
77,4IYP3Z8M,1431700058,6966.JP,9-9-2021,JP3892400007,Mitsui High-Tec,09/10/2021,Q2,2021,CONFIRMED,Unspecified,NEWS,None,None,12/01/2021 10:57:25 AM,12/01/2021 10:57:25 AM

In [3]:
wsh_eps

,event_id,company_id,stock_symbol,isin,company_name,announce_datetime,fiscal_year,quarter,quarter_end_date,currency,amount_oc,purl,created,updated,return_time,prelim_earnings_date,prelim_amount_from,prelim_amount_to,prelim_earnings_link
0,4IF903ZU,1431696910,EBON,KYG3R33A1063,Ebang International Holdings Inc.,10/01/2021 04:30 PM,2021,H1,06/30/2021,USD,-0.02,http://mmm.wallstreethorizon.com/u.asp?u=412038,05/01/2021 01:18:22 AM,10/01/2021 04:32:40 PM,01/10/2022 11:54:53 AM,NaN,NaN,NaN,NaN
1,4IKT03UY,1431695716,9793.JP,JP3485600005,Daiseki Co. Ltd.,10/01/2021,2022,Q2,08/31/2021,JPY,None,http://mmm.wallstreethorizon.com/u.asp?u=412032,07/01/2021 01:06:01 AM,10/01/2021 03:52:14 PM,01/10/2022 11:54:53 AM,NaN,NaN,NaN,NaN
2,4IA803W3,1431693492,JDW.GB,GB0001638955,JD Wetherspoon Plc,10/01/2021,2021,H2,07/25/2021,GBP,None,http://mmm.wallstreethorizon.com/u.asp?u=412008,03/20/2021 01:01:55 AM,10/01/2021 10:32:37 AM,01/10/2022 11:54:53 AM,NaN,NaN,NaN,NaN
3,4IWJ3MYS,1431692474,CA:HIVE,CA43366H1001,HIVE Blockchain Technologies Ltd.,10/01/2021 08:35 PM,2022,Q1,06/30/2021,USD,0.05,http://mmm.wallstreethorizon.com/u.asp?u=426138,11/23/2021 11:30:25 AM,11/23/2021 11:35:36 AM,01/10/2022 11:54:53 AM,NaN,NaN,NaN,NaN
4,4IF903XP,1431696478,ANPC,US03635R1077,"AnPac Bio-Medical Science Co., Ltd.",10/01/2021 07:30 AM,2021,H1,06/30/2021,USD,None,http://mmm.wallstreethorizon.com/u.asp?u=411968,05/01/2021 01:18:22 AM,10/01/2021 07:33:31 AM,01/10/2022 11:54:53 AM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,4IIA03WP,1431682086,VRNT,US92343X1000,Verint Systems Inc.,09/09/2021 04:05 PM,2022,Q2,07/31/2021,USD,0.58,http://mmm.wallstreethorizon.com/u.asp?u=410395,06/10/2021 01:05:11 AM,09/09/2021 04:19:17 PM,01/09/2022 11:24:52 AM,None,None,None,None
75,4IIA03VY,1431694739,KLXE,US48253L2051,KLX Energy Services Holdings Inc,09/09/2021 04:15 PM,2021,Q2,07/31/2021,USD,-2.98,http://mmm.wallstreethorizon.com/u.asp?u=410403,06/10/2021 01:05:11 AM,09/09/2021 04:29:37 PM,01/09/2022 11:24:52 AM,None,None,None,None
76,4IIC03V1,1431693155,9603.JP,JP3160740001,"H.I.S. Co. Ltd.,",09/10/2021,2021,Q3,07/31/2021,JPY,None,http://mmm.wallstreethorizon.com/u.asp?u=410462,06/12/2021 01:06:23 AM,09/10/2021 11:37:21 AM,01/09/2022 11:24:52 AM,None,None,None,None
77,4IQM1LRM,1431699236,OMGA,US68217N1054,"Omega Therapeutics, Inc.",09/10/2021 07:00 AM,2021,Q2,06/30/2021,USD,-3.36,http://mmm.wallstreethorizon.com/u.asp?u=410439,09/10/2021 07:03:16 AM,09/10/2021 07:03:47 AM,01/09/2022 11:24:52 AM,None,None,None,None
78,4IQP2HSV,1431697541,INAB,US45674E1091,"IN8bio, Inc.",09/10/2021 04:15 PM,2021,Q2,06/30/2021,USD,-1,http://mmm.wallstreethorizon.com/u.asp?u=410533,09/13/2021 11:28:30 AM,09/13/2021 11:29:08 AM,01/09/2022 11:24:52 AM,None,None,None,None

In [4]:
"""
Testing - whether stock symbol should be htick or ctick

NOTE ToDo: make sure to test this on another ticker that changed tickers
more recently! 

Found another test company with a very current ticker change
(and no isin or cusip change in CRSP DSENAMES) - Coterra Energy. 
Swapped ticker from COG to CTRA in October 4 2021. 

"""
wsh_earn[wsh_earn['stock_symbol']=="COG"]
wsh_earn[wsh_earn['stock_symbol'] == "CTRA"]

,event_id,company_id,stock_symbol,asofdate,isin,company_name,earnings_date,quarter,fiscal_year,earnings_date_status,time_of_day,audit_source,announce_datetime,prelim_earnings_date,updated,created
523,42XO002X,479,CTRA,11-2-2021,US1270971039,Coterra Energy Inc,11/03/2021,Q3,2021,CONFIRMED,Before Market,NEWS,10/14/2021 04:06 PM,None,11/04/2021 02:13:35 AM,04/28/2019 12:38:17 AM
146,42XO002X,479,CTRA,11-3-2021,US1270971039,Coterra Energy Inc,11/03/2021,Q3,2021,CONFIRMED,Before Market,NEWS,10/14/2021 04:06 PM,None,11/04/2021 02:13:35 AM,04/28/2019 12:38:17 AM

In [5]:
"""
Gathering files from history. 

History WSH files are saved in a folder in OneDrive, containing CSVs. 
Legacy hisotirc files were in Dropbox, under analogous names. 

The directory path in both places points to WSH/Data/hist_20210902. 

"""
histpth = pth + "/hist_20210902"
os.chdir(histpth)
earn_list = []
eps_list = []

earn_f = glob.glob("earnings*.csv")
eps_f = glob.glob("eps*.csv")

for f in earn_f:
    earn_list.append(pd.read_csv(os.path.join(histpth, f)))
    
for f in eps_f:
    eps_list.append(pd.read_csv(os.path.join(histpth, f)))
    
earnhist = pd.concat(earn_list)
epshist = pd.concat(eps_list)
earnhist

C:\Users\clj585\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\clj585\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\clj585\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\clj585\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (15,16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\clj585\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,event_id,company_id,stock_symbol,company_name,stock_exchange,earnings_date,quarter,fiscal_year,earnings_date_status,updated,time_of_day,asofdate,quarter_end_date,announce_datetime,audit_source,filing_due_date,isin,prelim_earnings_date,announcement_url,disclaimer
0,3VAF00T7,2,EW,Edwards Lifesciences Corp,NYSE,2/2/2006,Q4,2005.0,Unconfirmed,1/30/2006,NaN,20060102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,4,HBC,HSBC Holdings plc,NYSE,3/6/2006,Q4,2005.0,Confirmed,NaN,Before Market,20060102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3VAF00VY,5,SHLM,A. Schulman Inc.,NSDQ,1/6/2006,Q1,2006.0,Confirmed,12/17/2005 10:34:14 AM,Before Market,20060102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,6,BLC,Belo,NYSE,2/6/2006,Q4,2005.0,Unconfirmed,NaN,NaN,20060102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,8,ATX,AT Cross Co,AMEX,2/16/2006,Q4,2005.0,Inferred,NaN,NaN,20060102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2172748,4306001N,1431686560,ZXAIY,China Zenix Auto International Limited,OTC,11/30/2021,Q3,2021.0,UNCONFIRMED,09/01/2021 07:29:44 AM,Before Market,20210902,09/30/2021,NaN,BASE,NaN,US16951E1047,NaN,NaN,N
2172749,4IFM2TU4,1431698581,ZY,Zymergen Inc.,NSDQ,11/15/2021,Q3,2021.0,UNCONFIRMED,08/17/2021 11:45:40 AM,After Market,20210902,09/30/2021,NaN,BASE,11/15/2021,US98985X1000,NaN,NaN,N
2172750,42ZS009R,1431691745,ZYME,Zymeworks Inc.,NYSE,11/02/2021,Q3,2021.0,UNCONFIRMED,08/05/2021 01:06:45 AM,After Market,20210902,09/30/2021,NaN,BASE,11/09/2021,CA98985W1023,NaN,NaN,N
2172751,42ZY00C1,1431687702,ZYNE,"Zynerba Pharmaceuticals, Inc.",NSDQ,11/08/2021,Q3,2021.0,UNCONFIRMED,08/10/2021 01:06:51 AM,Before Market,20210902,09/30/2021,NaN,BASE,11/15/2021,US98986X1090,NaN,NaN,N
2172752,42ZQ007U,1431692892,ZYXI,"Zynex, Inc.",NSDQ,10/26/2021,Q3,2021.0,UNCONFIRMED,07/30/2021 01:08:50 AM,After Market,20210902,09/30/2021,NaN,BASE,11/15/2021,US98986M1036,NaN,NaN,N

In [6]:
"""
Rejoin historical data from above with previously concatenated parquet files 
to get data from 2006 to current. 

"""
wsh_earn = pd.concat([wsh_earn, earnhist])
wsh_eps = pd.concat([wsh_eps, epshist])

"""
Check and dedupe both data frames! 
This is due to overlapping dates hopefully. 

"""
wsh_earn = wsh_earn.drop_duplicates()

# Repeat same duplicate drop on wsh_eps (probably overlapping dates)
wsh_eps = wsh_eps.drop_duplicates()

wsh_earn

,event_id,company_id,stock_symbol,asofdate,isin,company_name,earnings_date,quarter,fiscal_year,earnings_date_status,...,audit_source,announce_datetime,prelim_earnings_date,updated,created,stock_exchange,quarter_end_date,filing_due_date,announcement_url,disclaimer
0,3VLF70OU,1431693492,JDW.GB,10-1-2021,GB0001638955,JD Wetherspoon Plc,10/01/2021,H2,2021,CONFIRMED,...,NEWS,07/12/2021,NaN,10/02/2021 01:13:07 AM,09/15/2018 09:15:56 AM,NaN,NaN,NaN,NaN,NaN
1,432UBI6H,1431695716,9793.JP,10-1-2021,JP3485600005,Daiseki Co. Ltd.,10/01/2021,Q2,2022,CONFIRMED,...,NEWS,08/25/2021,NaN,10/02/2021 01:13:07 AM,06/14/2019 10:57:19 AM,NaN,NaN,NaN,NaN,NaN
2,4IQK55K7,1431699366,KOF.FR,10-1-2021,FR0004007813,Kaufman & Broad,10/01/2021,Q3,2021,CONFIRMED,...,NEWS,07/30/2021,NaN,10/02/2021 09:49:53 AM,09/08/2021 04:22:18 PM,NaN,NaN,NaN,NaN,NaN
3,4AVG1QHW,1431696478,ANPC,10-1-2021,US03635R1077,"AnPac Bio-Medical Science Co., Ltd.",10/01/2021,H1,2021,CONFIRMED,...,NEWS,10/01/2021 07:30 AM,NaN,10/02/2021 01:13:07 AM,07/16/2020 08:51:51 AM,NaN,NaN,NaN,NaN,NaN
4,4IQP3M6J,1431699533,7965.JP,10-1-2021,JP3437400009,Zojirushi,10/01/2021,Q3,2021,CONFIRMED,...,NEWS,None,NaN,10/02/2021 01:13:07 AM,09/13/2021 03:38:36 PM,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2172748,4306001N,1431686560,ZXAIY,20210902,US16951E1047,China Zenix Auto International Limited,11/30/2021,Q3,2021.0,UNCONFIRMED,...,BASE,NaN,NaN,09/01/2021 07:29:44 AM,NaN,OTC,09/30/2021,NaN,NaN,N
2172749,4IFM2TU4,1431698581,ZY,20210902,US98985X1000,Zymergen Inc.,11/15/2021,Q3,2021.0,UNCONFIRMED,...,BASE,NaN,NaN,08/17/2021 11:45:40 AM,NaN,NSDQ,09/30/2021,11/15/2021,NaN,N
2172750,42ZS009R,1431691745,ZYME,20210902,CA98985W1023,Zymeworks Inc.,11/02/2021,Q3,2021.0,UNCONFIRMED,...,BASE,NaN,NaN,08/05/2021 01:06:45 AM,NaN,NYSE,09/30/2021,11/09/2021,NaN,N
2172751,42ZY00C1,1431687702,ZYNE,20210902,US98986X1090,"Zynerba Pharmaceuticals, Inc.",11/08/2021,Q3,2021.0,UNCONFIRMED,...,BASE,NaN,NaN,08/10/2021 01:06:51 AM,NaN,NSDQ,09/30/2021,11/15/2021,NaN,N
2172752,42ZQ007U,1431692892,ZYXI,20210902,US98986M1036,"Zynex, Inc.",10/26/2021,Q3,2021.0,UNCONFIRMED,...,BASE,NaN,NaN,07/30/2021 01:08:50 AM,NaN,NSDQ,09/30/2021,11/15/2021,NaN,N

In [7]:
"""
WSH earnings files - fixing column data types 
and subsetting columns taken care of here. 

"""
# Filter out columns and renaming
colskeep = ['event_id', 'company_id', 'stock_symbol', 
            'asofdate', 'isin', 'quarter', 'fiscal_year', 
            'earnings_date_status', 'time_of_day', 'announce_datetime', 
            'updated']
colmap = {"company_id" : "wsh_id", "stock_symbol":"hticker", "isin":"isin",
         "quarter": "fqtr", "fiscal_year" :"fyear", "announce_datetime":"exp_ea_datetime", 
         "asofdate":"date"}
wsh_earn2 = wsh_earn[colskeep]
wsh_earn2 = wsh_earn2.rename(columns = colmap)

# Define as strings
wsh_earn2[['wsh_id', "hticker", "fqtr", "exp_ea_datetime", "isin",
         "time_of_day", "date"]] = wsh_earn2[['wsh_id', "hticker", "fqtr", "exp_ea_datetime", "isin",
                                              "time_of_day", "date"]].astype("string")

# Input this as pandas date time stamp
wsh_earn2['exp_ea_datetime'] = pd.to_datetime(wsh_earn2['exp_ea_datetime'])
wsh_earn2

,event_id,wsh_id,hticker,date,isin,fqtr,fyear,earnings_date_status,time_of_day,exp_ea_datetime,updated
0,3VLF70OU,1431693492,JDW.GB,10-1-2021,GB0001638955,H2,2021,CONFIRMED,Unspecified,2021-07-12 00:00:00,10/02/2021 01:13:07 AM
1,432UBI6H,1431695716,9793.JP,10-1-2021,JP3485600005,Q2,2022,CONFIRMED,Unspecified,2021-08-25 00:00:00,10/02/2021 01:13:07 AM
2,4IQK55K7,1431699366,KOF.FR,10-1-2021,FR0004007813,Q3,2021,CONFIRMED,Unspecified,2021-07-30 00:00:00,10/02/2021 09:49:53 AM
3,4AVG1QHW,1431696478,ANPC,10-1-2021,US03635R1077,H1,2021,CONFIRMED,Before Market,2021-10-01 07:30:00,10/02/2021 01:13:07 AM
4,4IQP3M6J,1431699533,7965.JP,10-1-2021,JP3437400009,Q3,2021,CONFIRMED,Unspecified,NaT,10/02/2021 01:13:07 AM
...,...,...,...,...,...,...,...,...,...,...,...
2172748,4306001N,1431686560,ZXAIY,20210902,US16951E1047,Q3,2021.0,UNCONFIRMED,Before Market,NaT,09/01/2021 07:29:44 AM
2172749,4IFM2TU4,1431698581,ZY,20210902,US98985X1000,Q3,2021.0,UNCONFIRMED,After Market,NaT,08/17/2021 11:45:40 AM
2172750,42ZS009R,1431691745,ZYME,20210902,CA98985W1023,Q3,2021.0,UNCONFIRMED,After Market,NaT,08/05/2021 01:06:45 AM
2172751,42ZY00C1,1431687702,ZYNE,20210902,US98986X1090,Q3,2021.0,UNCONFIRMED,Before Market,NaT,08/10/2021 01:06:51 AM
2172752,42ZQ007U,1431692892,ZYXI,20210902,US98986M1036,Q3,2021.0,UNCONFIRMED,After Market,NaT,07/30/2021 01:08:50 AM

In [8]:
"""
Earnings columns - more processing for columns that 
contain information about fiscal period. 

The quarter and fiscal year are available. Note that the foreign 
companies have their own reporting frequencies and notation, such as 
semiannual or annual basis (H, H1 and H2).

"""
wsh_earn2['fyear'] = wsh_earn2['fyear'].astype(float)
wsh_earn2['fyear'] = wsh_earn2['fyear'].astype("Int64")

# Adjust the NA stuff in the time of day column 
wsh_earn2['time_of_day'].fillna("Not Available", inplace=True)

# Adjust the time of day flags to be consistent 
wsh_earn2['time_of_day'] = np.where(wsh_earn2['time_of_day'] == "After Market", "PC", 
                                   wsh_earn2['time_of_day'])
wsh_earn2['time_of_day'] = np.where(wsh_earn2['time_of_day'] == "Before Market", "PO", 
                                   wsh_earn2['time_of_day'])
wsh_earn2['time_of_day'] = np.where(wsh_earn2['time_of_day'] == "During Market", "RH", 
                                   wsh_earn2['time_of_day'])
wsh_earn2['time_of_day'] = np.where(wsh_earn2['time_of_day'].str.contains("Unspecified", case=False), 
                                   "Not Available", wsh_earn2['time_of_day'])

wsh_earn2

,event_id,wsh_id,hticker,date,isin,fqtr,fyear,earnings_date_status,time_of_day,exp_ea_datetime,updated
0,3VLF70OU,1431693492,JDW.GB,10-1-2021,GB0001638955,H2,2021,CONFIRMED,Not Available,2021-07-12 00:00:00,10/02/2021 01:13:07 AM
1,432UBI6H,1431695716,9793.JP,10-1-2021,JP3485600005,Q2,2022,CONFIRMED,Not Available,2021-08-25 00:00:00,10/02/2021 01:13:07 AM
2,4IQK55K7,1431699366,KOF.FR,10-1-2021,FR0004007813,Q3,2021,CONFIRMED,Not Available,2021-07-30 00:00:00,10/02/2021 09:49:53 AM
3,4AVG1QHW,1431696478,ANPC,10-1-2021,US03635R1077,H1,2021,CONFIRMED,PO,2021-10-01 07:30:00,10/02/2021 01:13:07 AM
4,4IQP3M6J,1431699533,7965.JP,10-1-2021,JP3437400009,Q3,2021,CONFIRMED,Not Available,NaT,10/02/2021 01:13:07 AM
...,...,...,...,...,...,...,...,...,...,...,...
2172748,4306001N,1431686560,ZXAIY,20210902,US16951E1047,Q3,2021,UNCONFIRMED,PO,NaT,09/01/2021 07:29:44 AM
2172749,4IFM2TU4,1431698581,ZY,20210902,US98985X1000,Q3,2021,UNCONFIRMED,PC,NaT,08/17/2021 11:45:40 AM
2172750,42ZS009R,1431691745,ZYME,20210902,CA98985W1023,Q3,2021,UNCONFIRMED,PC,NaT,08/05/2021 01:06:45 AM
2172751,42ZY00C1,1431687702,ZYNE,20210902,US98986X1090,Q3,2021,UNCONFIRMED,PO,NaT,08/10/2021 01:06:51 AM
2172752,42ZQ007U,1431692892,ZYXI,20210902,US98986M1036,Q3,2021,UNCONFIRMED,PC,NaT,07/30/2021 01:08:50 AM

In [9]:
"""
Split apart the date & timestamp column (announce_datetime)
for the earnings dataset. Create exp_ea_date and exp_ea_time columns from this. 

"""
wsh_earn2['exp_ea_time'] = wsh_earn2['exp_ea_datetime'].dt.time
wsh_earn2['exp_ea_date'] = wsh_earn2['exp_ea_datetime'].dt.date

# Can absolutely handle the different formats of the date column (formerly asofdate)
wsh_earn2['date'] = pd.to_datetime(wsh_earn2['date']) 

# Generate hcusip and hcusip9 columns 
wsh_earn2['hcusip'] = wsh_earn2['isin'].str[2:10]
wsh_earn2['hcusip9'] = wsh_earn2['isin'].str[2:11]

wsh_earn2

,event_id,wsh_id,hticker,date,isin,fqtr,fyear,earnings_date_status,time_of_day,exp_ea_datetime,updated,exp_ea_time,exp_ea_date,hcusip,hcusip9
0,3VLF70OU,1431693492,JDW.GB,2021-10-01,GB0001638955,H2,2021,CONFIRMED,Not Available,2021-07-12 00:00:00,10/02/2021 01:13:07 AM,00:00:00,2021-07-12,00016389,000163895
1,432UBI6H,1431695716,9793.JP,2021-10-01,JP3485600005,Q2,2022,CONFIRMED,Not Available,2021-08-25 00:00:00,10/02/2021 01:13:07 AM,00:00:00,2021-08-25,34856000,348560000
2,4IQK55K7,1431699366,KOF.FR,2021-10-01,FR0004007813,Q3,2021,CONFIRMED,Not Available,2021-07-30 00:00:00,10/02/2021 09:49:53 AM,00:00:00,2021-07-30,00040078,000400781
3,4AVG1QHW,1431696478,ANPC,2021-10-01,US03635R1077,H1,2021,CONFIRMED,PO,2021-10-01 07:30:00,10/02/2021 01:13:07 AM,07:30:00,2021-10-01,03635R10,03635R107
4,4IQP3M6J,1431699533,7965.JP,2021-10-01,JP3437400009,Q3,2021,CONFIRMED,Not Available,NaT,10/02/2021 01:13:07 AM,NaT,NaT,34374000,343740000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2172748,4306001N,1431686560,ZXAIY,2021-09-02,US16951E1047,Q3,2021,UNCONFIRMED,PO,NaT,09/01/2021 07:29:44 AM,NaN,NaN,16951E10,16951E104
2172749,4IFM2TU4,1431698581,ZY,2021-09-02,US98985X1000,Q3,2021,UNCONFIRMED,PC,NaT,08/17/2021 11:45:40 AM,NaN,NaN,98985X10,98985X100
2172750,42ZS009R,1431691745,ZYME,2021-09-02,CA98985W1023,Q3,2021,UNCONFIRMED,PC,NaT,08/05/2021 01:06:45 AM,NaN,NaN,98985W10,98985W102
2172751,42ZY00C1,1431687702,ZYNE,2021-09-02,US98986X1090,Q3,2021,UNCONFIRMED,PO,NaT,08/10/2021 01:06:51 AM,NaN,NaN,98986X10,98986X109
2172752,42ZQ007U,1431692892,ZYXI,2021-09-02,US98986M1036,Q3,2021,UNCONFIRMED,PC,NaT,07/30/2021 01:08:50 AM,NaN,NaN,98986M10,98986M103

In [10]:
"""
Earnings data - WSH uses the dotted style to denote tickers share classes. 
Meanwhile, preferred shares and other international entities are denoted
as a prefix before the colon. 

Process and split tickers here.  

"""
# Longer itertive process here
wsh_earn2["step1"] = wsh_earn2['hticker'].str.lstrip("!")

# Then get rid of the suffix in step1 column to create step2
wsh_earn2[['step2', "suffix"]] = wsh_earn2['step1'].str.split("[/.]", n=1, expand=True)

# Get rid of the prefix before ":", but need to adjust
wsh_earn2[['prefix_unadj', "root_unadj"]] = wsh_earn2['step2'].str.split("[/:]", n=1, expand=True)

# If there is no colon, then the root should be equal to what's in the prefix_unadj column
wsh_earn2['root'] = np.where(wsh_earn2['hticker'].str.contains(":"),
                            wsh_earn2['root_unadj'],  wsh_earn2['prefix_unadj'])

# If there is no colon, then the prefix should be blank as well
wsh_earn2['prefix'] = np.where(wsh_earn2['hticker'].str.contains(":"), 
                               wsh_earn2['prefix_unadj'], "")
wsh_earn2['suffix'] = wsh_earn2['suffix'].fillna("")

wsh_earn2 = wsh_earn2[['date', 'event_id', 'wsh_id', 'hticker', 'fqtr', 'fyear', 
                      'time_of_day', 'exp_ea_datetime', 'exp_ea_date', 'exp_ea_time', 
                      'hcusip', 'hcusip9', 'suffix', 'root', 'prefix']]

In [11]:
wsh_earn2[wsh_earn2['hticker']=="BRK.A"]
# One checking example
wsh_earn2[wsh_earn2['hticker']=="CA:HIVE"]

,date,event_id,wsh_id,hticker,fqtr,fyear,time_of_day,exp_ea_datetime,exp_ea_date,exp_ea_time,hcusip,hcusip9,suffix,root,prefix
5,2021-10-01,42U90003,1431692474,CA:HIVE,Q1,2022,PC,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
226,2021-11-14,43DS878V,1431692474,CA:HIVE,Q2,2022,PC,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
527,2021-11-15,43DS878V,1431692474,CA:HIVE,Q2,2022,PC,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
41,2021-09-22,3VRE70UV,1431692474,CA:HIVE,Q4,2021,PC,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
28,2021-09-23,3VRE70UV,1431692474,CA:HIVE,Q4,2021,PC,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129300,2021-08-29,3VRE70UV,1431692474,CA:HIVE,Q4,2021,Not Available,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
2138540,2021-08-30,3VRE70UV,1431692474,CA:HIVE,Q4,2021,Not Available,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
2147782,2021-08-31,3VRE70UV,1431692474,CA:HIVE,Q4,2021,Not Available,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
2157028,2021-09-01,3VRE70UV,1431692474,CA:HIVE,Q4,2021,Not Available,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA
2166272,2021-09-02,3VRE70UV,1431692474,CA:HIVE,Q4,2021,Not Available,NaT,NaT,NaT,43366H10,43366H100,,HIVE,CA

In [12]:
wsh_earn2.columns

Index(['date', 'event_id', 'wsh_id', 'hticker', 'fqtr', 'fyear', 'time_of_day',
       'exp_ea_datetime', 'exp_ea_date', 'exp_ea_time', 'hcusip', 'hcusip9',
       'suffix', 'root', 'prefix'],
      dtype='object')

In [13]:
"""
WSH EPS files - fix column types and subsetting here. 

"""
# Saved desired columns and column name map 
colskeep = ['company_id', "stock_symbol", "announce_datetime", "fiscal_year", "isin",
           "quarter"]
colmap = {"company_id": "wsh_id", "stock_symbol":"hticker", "fiscal_year":"fyear", 
         "quarter":"fqtr", "announce_datetime" : "ea_datetime"}

# Subset and rename on EPS
wsh_eps = wsh_eps[colskeep]
wsh_eps = wsh_eps.rename(columns = colmap)

# String column types
wsh_eps[['wsh_id', "hticker", "fqtr", "isin",
         "ea_datetime"]]= wsh_eps[['wsh_id',"hticker", "fqtr","isin",
                                         "ea_datetime"]].astype('string')
wsh_eps

           wsh_id  hticker          ea_datetime fyear          isin fqtr
0      1431696910     EBON  10/01/2021 04:30 PM  2021  KYG3R33A1063   H1
1      1431695716  9793.JP           10/01/2021  2022  JP3485600005   Q2
2      1431693492   JDW.GB           10/01/2021  2021  GB0001638955   H2
3      1431692474  CA:HIVE  10/01/2021 08:35 PM  2022  CA43366H1001   Q1
4      1431696478     ANPC  10/01/2021 07:30 AM  2021  US03635R1077   H1
...           ...      ...                  ...   ...           ...  ...
19625  1431686385     MRIN  2021-07-30 16:15:00  2021  US56804T2050   Q2
19626  1431683029     BFIN  2021-07-30 16:16:00  2021  US06643P1049   Q2
19627       10799     MSEX  2021-07-30 16:17:00  2021  US5966801087   Q2
19628        1736      NPK  2021-07-30 16:20:00  2021  US6372151042   Q2
19629  1431687633     UUUU  2021-07-30 17:27:00  2021  CA2926717083   Q2

[406112 rows x 6 columns]

In [14]:
"""
Date and time formatting - split the announcement date and timestamp combined
column into 2 different columns on EPS dataset. 

"""
# Fiscal year as float first and then to Int 64 (because of the NAN values handling)
wsh_eps['fyear'] = wsh_eps['fyear'].astype(float)
wsh_eps['fyear'] = wsh_eps['fyear'].astype("Int64")

# Date and time conversions involving actual EA announcement dates
wsh_eps['ea_datetime'] = pd.to_datetime(wsh_eps['ea_datetime'])
wsh_eps['ea_time'] = wsh_eps['ea_datetime'].dt.time
wsh_eps['ea_date'] = wsh_eps['ea_datetime'].dt.date
wsh_eps

,wsh_id,hticker,ea_datetime,fyear,isin,fqtr,ea_time,ea_date
0,1431696910,EBON,2021-10-01 16:30:00,2021,KYG3R33A1063,H1,16:30:00,2021-10-01
1,1431695716,9793.JP,2021-10-01 00:00:00,2022,JP3485600005,Q2,00:00:00,2021-10-01
2,1431693492,JDW.GB,2021-10-01 00:00:00,2021,GB0001638955,H2,00:00:00,2021-10-01
3,1431692474,CA:HIVE,2021-10-01 20:35:00,2022,CA43366H1001,Q1,20:35:00,2021-10-01
4,1431696478,ANPC,2021-10-01 07:30:00,2021,US03635R1077,H1,07:30:00,2021-10-01
...,...,...,...,...,...,...,...,...
19625,1431686385,MRIN,2021-07-30 16:15:00,2021,US56804T2050,Q2,16:15:00,2021-07-30
19626,1431683029,BFIN,2021-07-30 16:16:00,2021,US06643P1049,Q2,16:16:00,2021-07-30
19627,10799,MSEX,2021-07-30 16:17:00,2021,US5966801087,Q2,16:17:00,2021-07-30
19628,1736,NPK,2021-07-30 16:20:00,2021,US6372151042,Q2,16:20:00,2021-07-30
19629,1431687633,UUUU,2021-07-30 17:27:00,2021,CA2926717083,Q2,17:27:00,2021-07-30

In [15]:
"""
Dotted ticker processing on EPS data frame, 
as well as taking care of prefixes. 

"""
# Longer itertive process here
wsh_eps["step1"] = wsh_eps['hticker'].str.lstrip("!")

# The check to make sure that this first step worked 
wsh_eps[wsh_eps['hticker'].str.contains("!")]
wsh_eps

# Then get rid of the colon ":" in step1 column to create step2
wsh_eps[['step2', "suffix"]] = wsh_eps['step1'].str.split("[/.]", n=1, 
                                                              expand=True)

# Last step!!! GRRR
wsh_eps[['prefix_unadj', "root_unadj"]] = wsh_eps['step2'].str.split("[/:]", n=1, 
                                                                     expand=True)

# Need to adjust things 
# If there is no colon, then the root should be equal to what's in the prefix_unadj column
wsh_eps['root'] = np.where(wsh_eps['hticker'].str.contains(":"),
                            wsh_eps['root_unadj'],  wsh_eps['prefix_unadj'])

# If there is no colon, then the prefix should be blank as well
wsh_eps['prefix'] = np.where(wsh_eps['hticker'].str.contains(":"), 
                               wsh_eps['prefix_unadj'], "")

# Fill out NA cells
wsh_eps['suffix'] = wsh_eps['suffix'].fillna("")
wsh_eps['prefix'] = wsh_eps['prefix'].fillna('')

# Handle isin to CUSIP conversions here
wsh_eps['hcusip9'] = wsh_eps['isin'].str[2:11]
wsh_eps['hcusip'] = wsh_eps['isin'].str[2:10]

wsh_eps = wsh_eps[["wsh_id","hticker","ea_datetime","fqtr","fyear",
                   "hcusip","hcusip9",
                   "ea_time","ea_date","prefix","root","suffix"]]

wsh_eps

,wsh_id,hticker,ea_datetime,fqtr,fyear,hcusip,hcusip9,ea_time,ea_date,prefix,root,suffix
0,1431696910,EBON,2021-10-01 16:30:00,H1,2021,G3R33A10,G3R33A106,16:30:00,2021-10-01,,EBON,
1,1431695716,9793.JP,2021-10-01 00:00:00,Q2,2022,34856000,348560000,00:00:00,2021-10-01,,9793,JP
2,1431693492,JDW.GB,2021-10-01 00:00:00,H2,2021,00016389,000163895,00:00:00,2021-10-01,,JDW,GB
3,1431692474,CA:HIVE,2021-10-01 20:35:00,Q1,2022,43366H10,43366H100,20:35:00,2021-10-01,CA,HIVE,
4,1431696478,ANPC,2021-10-01 07:30:00,H1,2021,03635R10,03635R107,07:30:00,2021-10-01,,ANPC,
...,...,...,...,...,...,...,...,...,...,...,...,...
19625,1431686385,MRIN,2021-07-30 16:15:00,Q2,2021,56804T20,56804T205,16:15:00,2021-07-30,,MRIN,
19626,1431683029,BFIN,2021-07-30 16:16:00,Q2,2021,06643P10,06643P104,16:16:00,2021-07-30,,BFIN,
19627,10799,MSEX,2021-07-30 16:17:00,Q2,2021,59668010,596680108,16:17:00,2021-07-30,,MSEX,
19628,1736,NPK,2021-07-30 16:20:00,Q2,2021,63721510,637215104,16:20:00,2021-07-30,,NPK,
19629,1431687633,UUUU,2021-07-30 17:27:00,Q2,2021,29267170,292671708,17:27:00,2021-07-30,,UUUU,

In [17]:
"""
Save both as parquet files.

"""
# Paths here 
pth1 = pth + "/wsh_earn_eadates.parquet"
pth2 = pth + "/wsh_eps_eadates.parquet"

# Save out as parquets in OneDrive
wsh_earn2.to_parquet(pth1)
wsh_eps.to_parquet(pth2)